<?php
/** @var \Stanislavz\LearnRoutes\Block\CustomLayout $block*/
?>

<div>
    <p>some content</p>
    <?php if ($block->getName()):?>
        <p><?= $block->getName(); ?></p>
    <?php endif;
    if ($block->getLastName()):?>
        <p><?= $block->getLastName(); ?></p>
    <?php endif;
    if ($block->getLinkToJson()):?>
        <p><a href="<?= $block->getLinkToJson(); ?>">Link To JSON</a></p>
    <?php endif; ?>
</div>
